[platformio]
default_envs = esp32dev-factory

[common]
lib_deps =
    symlink://../..
build_flags =
    -I ../../src
    -DFIRMNGIN_FACTORY_SERIAL=1
monitor_speed = 115200
board_upload.erase_all = true

[env:esp32dev-factory]
platform = espressif32@6.4.0
board = esp32dev
framework = arduino
lib_deps = ${common.lib_deps}
build_flags = ${common.build_flags}
monitor_speed = ${common.monitor_speed}

[env:esp8266-factory]
platform = espressif8266@4.2.1
board = esp12e
framework = arduino
lib_deps = ${common.lib_deps}
    rweather/Crypto @ ^0.4.0
build_flags = ${common.build_flags}
monitor_speed = ${common.monitor_speed}
